name: Deploy to EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 기존 백엔드 디렉토리 삭제 및 새로 클론
            echo "Removing old backend directory and cloning repository..."
            rm -rf ~/backend
            git clone https://github.com/FC-DEV-FinalProject/final-be-team4.git ~/backend
            cd ~/backend
            mkdir -p src/main/resources

            # secret.properties 파일 생성
            echo "Creating secret.properties file..."
            echo "${{ secrets.SECRET_PROPERTIES }}" > src/main/resources/secret.properties

            # StableFurnaceProject1.json 파일 생성
            echo "Creating StableFurnaceProject1.json file..."
            cat <<EOF > src/main/resources/StableFurnaceProject1.json
            {
              "type": "service_account",
              "project_id": "${{ secrets.PROJECT_ID }}",
              "private_key_id": "${{ secrets.PRIVATE_KEY_ID }}",
              "private_key": "${{ secrets.PRIVATE_KEY }}",
              "client_email": "${{ secrets.CLIENT_EMAIL }}",
              "client_id": "${{ secrets.CLIENT_ID }}",
              "auth_uri": "https://accounts.google.com/o/oauth2/auth",
              "token_uri": "${{ secrets.TOKEN_URI }}",
              "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
              "client_x509_cert_url": "${{ secrets.CLIENT_X509_CERT_URL }}",
              "universe_domain": "googleapis.com"
            }
            EOF

            # 의존성 설치 및 빌드 실행
            echo "Updating system and installing Java 17..."
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk

            echo "Building the project with Gradle..."
            chmod +x gradlew
            ./gradlew build -x test

            # 기존 애플리케이션 종료
            echo "Stopping existing application if running..."
            sudo pkill -f "java -jar" || echo "No application was running."

            # 새 애플리케이션 실행
            echo "Starting the new application..."
            nohup java -jar build/libs/*.jar > app.log 2>&1 &

            # 애플리케이션 실행 상태 확인
            echo "Checking application status..."
            ps aux | grep "java -jar" || echo "Application did not start correctly."

            # 종료 코드 명시
            exit 0
