name: Deploy to EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/backend
            git pull
            
            chmod +x gradlew
            ./gradlew build

            sudo pkill -f "java -jar"
            java -jar build/libs/tts_vc_web-0.0.1-SNAPSHOT.jar

      - name: Notify Slack - Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": ":white_check_mark: 백엔드 배포가 성공적으로 완료되었습니다."
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack - Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": ":x: 백엔드 배포 중 오류가 발생했습니다."
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

