name: Deploy to EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf ~/backend
            git clone https://github.com/FC-DEV-FinalProject/final-be-team4.git ~/backend
            cd ~/backend
            mkdir -p src/main/resources

            echo "${{ secrets.SECRET_PROPERTIES }}" > src/main/resources/secret.properties
            echo "${{ secrets.SOUND_JSON }}" > src/main/resources/StableFurnaceProject1.json


            chmod +x gradlew
            ./gradlew build -x test

            sudo pkill -f "java -jar"
            java -jar build/libs/tts_vc_web-0.0.1-SNAPSHOT.jar

