name: Gradle Test

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스 코드 체크아웃
      - uses: actions/checkout@v4

      # 2. JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # 3. gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 파일 생성 및 환경 설정
      - name: Create resource files
        run: |
          APP_DIR=src/main/resources
          echo "Creating resource directory at $APP_DIR"
          mkdir -p $APP_DIR

          # secret.properties 파일 생성
          echo "Creating secret.properties file..."
          echo "${{ secrets.SECRET_PROPERTIES }}" > $APP_DIR/secret.properties

          # StableFurnaceProject1.json 파일 생성
          echo "Creating StableFurnaceProject1.json file..."
          cat <<EOF > $APP_DIR/StableFurnaceProject1.json
          {
            "type": "service_account",
            "project_id": "${{ secrets.PROJECT_ID }}",
            "private_key_id": "${{ secrets.PRIVATE_KEY_ID }}",
            "private_key": "${{ secrets.PRIVATE_KEY }}",
            "client_email": "${{ secrets.CLIENT_EMAIL }}",
            "client_id": "${{ secrets.CLIENT_ID }}",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "${{ secrets.TOKEN_URI }}",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "${{ secrets.CLIENT_X509_CERT_URL }}",
            "universe_domain": "googleapis.com"
          }
          EOF

      # 5. 파일 검증
      - name: Verify resource files
        run: |
          echo "Verifying created resource files..."
          ls -l src/main/resources/

      # 6. Gradle 빌드 실행
      - name: Build with Gradle
        id: build
        run: ./gradlew build -x test

      # 7. Gradle 테스트 실행
      - name: Run tests
        run: ./gradlew test -Dspring.profiles.active=test