name: Gradle Test

on:
  # pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create properties files
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.SECRET_PROPERTIES }}" > src/main/resources/secret.properties
          echo "${{ secrets.SOUND_JSON }}" >  src/main/resources/sound-potion-440705-j8-cc85748343a6.json

      - name: Build with Gradle
        id: build
        run: ./gradlew build

      - name: Comment on PR if build fails
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '빌드에 실패했습니다. 에러 로그를 확인해주세요.'
            })
