name: Gradle Test

on:
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스 코드 체크아웃
      - uses: actions/checkout@v4

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # 3. gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. properties 및 JSON 파일 생성
      - name: Create properties files
        run: |
          echo "Creating necessary files..."
          mkdir -p src/main/resources

          # secret.properties 생성
          echo "${{ secrets.SECRET_PROPERTIES }}" > src/main/resources/secret.properties

          # StableFurnaceProject1.json 생성
          cat <<EOF > src/main/resources/StableFurnaceProject1.json
          {
            "type": "service_account",
            "project_id": "${{ secrets.PROJECT_ID }}",
            "private_key_id": "${{ secrets.PRIVATE_KEY_ID }}",
            "private_key": "${{ secrets.PRIVATE_KEY }}",
            "client_email": "${{ secrets.CLIENT_EMAIL }}",
            "client_id": "${{ secrets.CLIENT_ID }}",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "${{ secrets.TOKEN_URI }}",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "${{ secrets.CLIENT_X509_CERT_URL }}",
            "universe_domain": "googleapis.com"
          }
          EOF

      # 5. Gradle 빌드 실행
      - name: Build with Gradle
        id: build
        run: ./gradlew build
